name: m1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14  # M1 Mac
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install cmake open-mpi opencv eigen nlohmann-json cpprestsdk boost googletest

    - name: Configure
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: |
        cd build
        make

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure